
---
# Source: config-service/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: solemn-gerbil-config-service
  labels:
    chart: config-service-0.1.0
    release: solemn-gerbil
    heritage: Tiller
    component: config-service
data:
  bootstrap.yaml: |+
    spring:
      application:
        name: config-service

  application.yaml: |+
    server:
      port: 8088
    management:
      endpoints:
        web:
          exposure:
            include: "*"
          cors:
            allowed-origins: "*"
            allowed-methods: "*"
    
    spring:
      cloud:
        config:
          server:
            git:
              uri: https://github.com/kaybinwong/running-spring-boot-app-on-k8s
              search-paths: mircoservices/config-repo
        stream:
          default-binder: kafka
          kafka:
            binder:
              brokers: 192.168.64.134:9092
              zk-nodes: 192.168.64.168:2181

    eureka:
      instance:
        preferIpAddress: true
      client:
        enabled: true
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
          defaultZone: http://saucy-snake-registry-service-svc:8761/eureka
---
# Source: config-service/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: solemn-gerbil-config-service
  labels:
    chart: config-service-0.1.0
    release: solemn-gerbil
    heritage: Tiller
    component: config-service
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8088
    targetPort: 8088
    protocol: TCP
  selector:
    component: config-service
---
# Source: config-service/templates/deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: solemn-gerbil-config-service
  labels:
    chart: config-service-0.1.0
    release: solemn-gerbil
    heritage: Tiller
    component: config-service
spec:
  replicas:  1
  revisionHistoryLimit: 10
  template:
    metadata:
      labels:
        component: config-service
    spec:
      imagePullSecrets:
      - name: registry-secret
      containers:
      - name: config-service
        image: registry.cn-hangzhou.aliyuncs.com/kayb/config-service:v0.0.2
        imagePullPolicy: Always

        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8088
          initialDelaySeconds: 30
          periodSeconds: 300
          timeoutSeconds: 60
          successThreshold: 1
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8088
          initialDelaySeconds: 30
          periodSeconds: 300
          timeoutSeconds: 60
          successThreshold: 1
          failureThreshold: 5

        volumeMounts:
        - mountPath: /config
          name: config-service-data
      volumes:
      - name: config-service-data
        configMap:
          name: solemn-gerbil-config-service