
---
# Source: gateway-service/templates/service.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: exacerbated-hare-gateway-service
  labels:
    chart: gateway-service-0.1.0
    release: exacerbated-hare
    heritage: Tiller
    component: gateway-service
data:
  bootstrap.yaml: |+
    server:
      port: 8080
    spring:
      application:
        name: gateway-service
      cloud:
        config:
          discovery:
            enabled: true
            service-id: config-service
          profile: test
          label:  master

    eureka:
      instance:
        preferIpAddress: true
      client:
        enabled: true
        registerWithEureka: true
        serviceUrl:
          defaultZone: http://saucy-snake-registry-service-svc:8761/eureka
---
# Source: gateway-service/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: exacerbated-hare-gateway-service
  labels:
    chart: gateway-service-0.1.0
    release: exacerbated-hare
    heritage: Tiller
    k8s-app: gateway-service
spec:
  type: NodePort
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    k8s-app: gateway-service
---
# Source: gateway-service/templates/service.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: exacerbated-hare-gateway-service
  labels:
    chart: gateway-service-0.1.0
    release: exacerbated-hare
    heritage: Tiller
    k8s-app: gateway-service
spec:
  replicas:  1
  revisionHistoryLimit: 
  template:
    metadata:
      labels:
        k8s-app: gateway-service
    spec:
      imagePullSecrets:
      - name: registry-secret
      containers:
      - name: gateway-service
        image: registry.cn-hangzhou.aliyuncs.com/kayb/gateway-service:latest
        imagePullPolicy: Always

        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 300
          timeoutSeconds: 60
          successThreshold: 1
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 300
          timeoutSeconds: 60
          successThreshold: 1
          failureThreshold: 5

        volumeMounts:
        - mountPath: /config
          name: config

      volumes:
      - name: config
        configMap:
          name: exacerbated-hare-gateway-service