eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}

spring:
  cloud:
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers: 192.168.64.134:9092
          zk-nodes: 192.168.64.168:2181

management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"