server:
  port: ${SERVER_PORT:8761}

eureka:
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 10000
    wait-time-in-ms-when-sync-empty: 0
  client:
    enabled: true
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka/}

  instance:
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 10
    prefer-ip-address: false

spring:
  zipkin:
    base-url: http://localhost:9411