server:
  port: 8762

spring:
  application:
    name: service-registry

# 目前只有使用bus kafka，若是需要使用多个队列，可声明多个binder
  cloud:
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers: localhost:9092
          zk-nodes: localhost:2181

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://127.0.0.1:8762/eureka
  server:
    wait-time-in-ms-when-sync-empty: 0