# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 2
image:
  repository: registry.seedland.cc/inf/passport-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  name: 
  enabled: true
  type: ClusterIP
  externalPort: 8080
  internalPort: 8080

livenessProbe:
  initialDelaySeconds: 30
  periodSeconds: 300
  timeoutSeconds: 60
  successThreshold: 1
  failureThreshold: 5

readinessProbe:
  initialDelaySeconds: 30
  periodSeconds: 300
  timeoutSeconds: 60
  successThreshold: 1
  failureThreshold: 5

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: 

label: 
profile: 
discovery: 
  enabled: 
  serviceId: 