profile: "dev"

spring:
  rabbitmq:
    host: 192.168.64.216
    port: 5672
    username: admin
    password: shidi@datacenter

  zipkin:
    base-url: http://localhost:9411
 
  sleuth:
    sampler:
      probability: 1.0