profile: "dev"

spring:
  cloud:
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers: 192.168.64.168:9092
          zk-nodes: 192.168.64.168:2181
 
  sleuth:
    sampler:
      probability: 1.0