profile: "dev"

spring:
  cloud:
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers: localhost:9092
          zk-nodes: localhost:2181
 
  sleuth:
    sampler:
      probability: 1.0