---
spring:
  cloud:
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers: localhost:9092
          zkNodes: localhost:2181

  sleuth:
    enabled: false
    sampler:
      percentage: 0.1

server:
  port: 9411

#zipkin:
#  storage:
#    elasticsearch:
#      cluster: elasticsearch
#      index-replicas: 1
#      passwoord: 123456
#      hosts: localhost:9200
#      index: zipkin
#      index-shards: 1
#      username: elastic
#    type: elasticsearch