# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: registry.seedland.cc/inf/zipkin-service
  tag: latest
  pullPolicy: Always

service:
  name: "zipkin-service"
  enabled: true
  type: NodePort
  externalPort: 9411
  internalPort: 9411

livenessProbe:
  httpGet:
    path: /health
  initialDelaySeconds: 30
  periodSeconds: 300
  timeoutSeconds: 60
  successThreshold: 1
  failureThreshold: 5

readinessProbe:
  httpGet:
    path: /health
  initialDelaySeconds: 30
  periodSeconds: 300
  timeoutSeconds: 60
  successThreshold: 1
  failureThreshold: 5

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://saucy-snake-registry-service-svc:8761/eureka

label: master
profile: test
discovery: 
  enabled: true
  serviceId: config-service
